// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace OpenShift.DotNet.Service.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// ImageStreamImportStatus contains information about the status of an
    /// image stream import.
    /// </summary>
    public partial class Comgithubopenshiftoriginpkgimageapisimagev1ImageStreamImportStatus
    {
        /// <summary>
        /// Initializes a new instance of the
        /// Comgithubopenshiftoriginpkgimageapisimagev1ImageStreamImportStatus
        /// class.
        /// </summary>
        public Comgithubopenshiftoriginpkgimageapisimagev1ImageStreamImportStatus() { }

        /// <summary>
        /// Initializes a new instance of the
        /// Comgithubopenshiftoriginpkgimageapisimagev1ImageStreamImportStatus
        /// class.
        /// </summary>
        public Comgithubopenshiftoriginpkgimageapisimagev1ImageStreamImportStatus(IList<Comgithubopenshiftoriginpkgimageapisimagev1ImageImportStatus> images = default(IList<Comgithubopenshiftoriginpkgimageapisimagev1ImageImportStatus>), Comgithubopenshiftoriginpkgimageapisimagev1ImageStream import = default(Comgithubopenshiftoriginpkgimageapisimagev1ImageStream), Comgithubopenshiftoriginpkgimageapisimagev1RepositoryImportStatus repository = default(Comgithubopenshiftoriginpkgimageapisimagev1RepositoryImportStatus))
        {
            Images = images;
            Import = import;
            Repository = repository;
        }

        /// <summary>
        /// Images is set with the result of importing spec.images
        /// </summary>
        [JsonProperty(PropertyName = "images")]
        public IList<Comgithubopenshiftoriginpkgimageapisimagev1ImageImportStatus> Images { get; set; }

        /// <summary>
        /// Import is the image stream that was successfully updated or
        /// created when 'to' was set.
        /// </summary>
        [JsonProperty(PropertyName = "import")]
        public Comgithubopenshiftoriginpkgimageapisimagev1ImageStream Import { get; set; }

        /// <summary>
        /// Repository is set if spec.repository was set to the outcome of the
        /// import
        /// </summary>
        [JsonProperty(PropertyName = "repository")]
        public Comgithubopenshiftoriginpkgimageapisimagev1RepositoryImportStatus Repository { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (this.Images != null)
            {
                foreach (var element in this.Images)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
            if (this.Import != null)
            {
                this.Import.Validate();
            }
        }
    }
}
