// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace OpenShift.DotNet.Service.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// ProjectStatus is information about the current status of a Project
    /// </summary>
    public partial class Comgithubopenshiftoriginpkgprojectapisprojectv1ProjectStatus
    {
        /// <summary>
        /// Initializes a new instance of the
        /// Comgithubopenshiftoriginpkgprojectapisprojectv1ProjectStatus
        /// class.
        /// </summary>
        public Comgithubopenshiftoriginpkgprojectapisprojectv1ProjectStatus() { }

        /// <summary>
        /// Initializes a new instance of the
        /// Comgithubopenshiftoriginpkgprojectapisprojectv1ProjectStatus
        /// class.
        /// </summary>
        public Comgithubopenshiftoriginpkgprojectapisprojectv1ProjectStatus(string phase = default(string))
        {
            Phase = phase;
        }

        /// <summary>
        /// Phase is the current lifecycle phase of the project
        /// </summary>
        [JsonProperty(PropertyName = "phase")]
        public string Phase { get; set; }

    }
}
