// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace OpenShift.DotNet.Service.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// ServiceAccountPodSecurityPolicyReviewStatus represents ServiceAccount
    /// name and related review status
    /// </summary>
    public partial class Comgithubopenshiftoriginpkgsecurityapissecurityv1ServiceAccountPodSecurityPolicyReviewStatus
    {
        /// <summary>
        /// Initializes a new instance of the
        /// Comgithubopenshiftoriginpkgsecurityapissecurityv1ServiceAccountPodSecurityPolicyReviewStatus
        /// class.
        /// </summary>
        public Comgithubopenshiftoriginpkgsecurityapissecurityv1ServiceAccountPodSecurityPolicyReviewStatus() { }

        /// <summary>
        /// Initializes a new instance of the
        /// Comgithubopenshiftoriginpkgsecurityapissecurityv1ServiceAccountPodSecurityPolicyReviewStatus
        /// class.
        /// </summary>
        public Comgithubopenshiftoriginpkgsecurityapissecurityv1ServiceAccountPodSecurityPolicyReviewStatus(string name, Iok8skubernetespkgapiv1ObjectReference allowedBy = default(Iok8skubernetespkgapiv1ObjectReference), string reason = default(string), Iok8skubernetespkgapiv1PodTemplateSpec template = default(Iok8skubernetespkgapiv1PodTemplateSpec))
        {
            AllowedBy = allowedBy;
            Name = name;
            Reason = reason;
            Template = template;
        }

        /// <summary>
        /// allowedBy is a reference to the rule that allows the
        /// PodTemplateSpec. A rule can be a SecurityContextConstraint or a
        /// PodSecurityPolicy A `nil`, indicates that it was denied.
        /// </summary>
        [JsonProperty(PropertyName = "allowedBy")]
        public Iok8skubernetespkgapiv1ObjectReference AllowedBy { get; set; }

        /// <summary>
        /// name contains the allowed and the denied ServiceAccount name
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// A machine-readable description of why this operation is in the
        /// "Failure" status. If this value is empty there is no information
        /// available.
        /// </summary>
        [JsonProperty(PropertyName = "reason")]
        public string Reason { get; set; }

        /// <summary>
        /// template is the PodTemplateSpec after the defaulting is applied.
        /// </summary>
        [JsonProperty(PropertyName = "template")]
        public Iok8skubernetespkgapiv1PodTemplateSpec Template { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (Name == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Name");
            }
            if (this.Template != null)
            {
                this.Template.Validate();
            }
        }
    }
}
