// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace OpenShift.DotNet.Service.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// CustomDeploymentStrategyParams are the input to the Custom deployment
    /// strategy.
    /// </summary>
    public partial class Comgithubopenshiftoriginpkgappsapisappsv1CustomDeploymentStrategyParams
    {
        /// <summary>
        /// Initializes a new instance of the
        /// Comgithubopenshiftoriginpkgappsapisappsv1CustomDeploymentStrategyParams
        /// class.
        /// </summary>
        public Comgithubopenshiftoriginpkgappsapisappsv1CustomDeploymentStrategyParams() { }

        /// <summary>
        /// Initializes a new instance of the
        /// Comgithubopenshiftoriginpkgappsapisappsv1CustomDeploymentStrategyParams
        /// class.
        /// </summary>
        public Comgithubopenshiftoriginpkgappsapisappsv1CustomDeploymentStrategyParams(IList<string> command = default(IList<string>), IList<Iok8skubernetespkgapiv1EnvVar> environment = default(IList<Iok8skubernetespkgapiv1EnvVar>), string image = default(string))
        {
            Command = command;
            Environment = environment;
            Image = image;
        }

        /// <summary>
        /// Command is optional and overrides CMD in the container Image.
        /// </summary>
        [JsonProperty(PropertyName = "command")]
        public IList<string> Command { get; set; }

        /// <summary>
        /// Environment holds the environment which will be given to the
        /// container for Image.
        /// </summary>
        [JsonProperty(PropertyName = "environment")]
        public IList<Iok8skubernetespkgapiv1EnvVar> Environment { get; set; }

        /// <summary>
        /// Image specifies a Docker image which can carry out a deployment.
        /// </summary>
        [JsonProperty(PropertyName = "image")]
        public string Image { get; set; }

    }
}
