// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace OpenShift.DotNet.Service.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// PodSecurityPolicySelfSubjectReviewSpec contains specification for
    /// PodSecurityPolicySelfSubjectReview.
    /// </summary>
    public partial class Comgithubopenshiftoriginpkgsecurityapissecurityv1PodSecurityPolicySelfSubjectReviewSpec
    {
        /// <summary>
        /// Initializes a new instance of the
        /// Comgithubopenshiftoriginpkgsecurityapissecurityv1PodSecurityPolicySelfSubjectReviewSpec
        /// class.
        /// </summary>
        public Comgithubopenshiftoriginpkgsecurityapissecurityv1PodSecurityPolicySelfSubjectReviewSpec() { }

        /// <summary>
        /// Initializes a new instance of the
        /// Comgithubopenshiftoriginpkgsecurityapissecurityv1PodSecurityPolicySelfSubjectReviewSpec
        /// class.
        /// </summary>
        public Comgithubopenshiftoriginpkgsecurityapissecurityv1PodSecurityPolicySelfSubjectReviewSpec(Iok8skubernetespkgapiv1PodTemplateSpec template)
        {
            Template = template;
        }

        /// <summary>
        /// template is the PodTemplateSpec to check.
        /// </summary>
        [JsonProperty(PropertyName = "template")]
        public Iok8skubernetespkgapiv1PodTemplateSpec Template { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (Template == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Template");
            }
            if (this.Template != null)
            {
                this.Template.Validate();
            }
        }
    }
}
