// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace OpenShift.DotNet.Service.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// LifecycleHook defines a specific deployment lifecycle action. Only one
    /// type of action may be specified at any time.
    /// </summary>
    public partial class Comgithubopenshiftoriginpkgappsapisappsv1LifecycleHook
    {
        /// <summary>
        /// Initializes a new instance of the
        /// Comgithubopenshiftoriginpkgappsapisappsv1LifecycleHook class.
        /// </summary>
        public Comgithubopenshiftoriginpkgappsapisappsv1LifecycleHook() { }

        /// <summary>
        /// Initializes a new instance of the
        /// Comgithubopenshiftoriginpkgappsapisappsv1LifecycleHook class.
        /// </summary>
        public Comgithubopenshiftoriginpkgappsapisappsv1LifecycleHook(string failurePolicy, Comgithubopenshiftoriginpkgappsapisappsv1ExecNewPodHook execNewPod = default(Comgithubopenshiftoriginpkgappsapisappsv1ExecNewPodHook), IList<Comgithubopenshiftoriginpkgappsapisappsv1TagImageHook> tagImages = default(IList<Comgithubopenshiftoriginpkgappsapisappsv1TagImageHook>))
        {
            ExecNewPod = execNewPod;
            FailurePolicy = failurePolicy;
            TagImages = tagImages;
        }

        /// <summary>
        /// ExecNewPod specifies the options for a lifecycle hook backed by a
        /// pod.
        /// </summary>
        [JsonProperty(PropertyName = "execNewPod")]
        public Comgithubopenshiftoriginpkgappsapisappsv1ExecNewPodHook ExecNewPod { get; set; }

        /// <summary>
        /// FailurePolicy specifies what action to take if the hook fails.
        /// </summary>
        [JsonProperty(PropertyName = "failurePolicy")]
        public string FailurePolicy { get; set; }

        /// <summary>
        /// TagImages instructs the deployer to tag the current image
        /// referenced under a container onto an image stream tag.
        /// </summary>
        [JsonProperty(PropertyName = "tagImages")]
        public IList<Comgithubopenshiftoriginpkgappsapisappsv1TagImageHook> TagImages { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (FailurePolicy == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "FailurePolicy");
            }
            if (this.ExecNewPod != null)
            {
                this.ExecNewPod.Validate();
            }
            if (this.TagImages != null)
            {
                foreach (var element in this.TagImages)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
