// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace OpenShift.DotNet.Service.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// TemplateInstanceStatus describes the current state of a
    /// TemplateInstance.
    /// </summary>
    public partial class Comgithubopenshiftoriginpkgtemplateapistemplatev1TemplateInstanceStatus
    {
        /// <summary>
        /// Initializes a new instance of the
        /// Comgithubopenshiftoriginpkgtemplateapistemplatev1TemplateInstanceStatus
        /// class.
        /// </summary>
        public Comgithubopenshiftoriginpkgtemplateapistemplatev1TemplateInstanceStatus() { }

        /// <summary>
        /// Initializes a new instance of the
        /// Comgithubopenshiftoriginpkgtemplateapistemplatev1TemplateInstanceStatus
        /// class.
        /// </summary>
        public Comgithubopenshiftoriginpkgtemplateapistemplatev1TemplateInstanceStatus(IList<Comgithubopenshiftoriginpkgtemplateapistemplatev1TemplateInstanceCondition> conditions = default(IList<Comgithubopenshiftoriginpkgtemplateapistemplatev1TemplateInstanceCondition>), IList<Comgithubopenshiftoriginpkgtemplateapistemplatev1TemplateInstanceObject> objects = default(IList<Comgithubopenshiftoriginpkgtemplateapistemplatev1TemplateInstanceObject>))
        {
            Conditions = conditions;
            Objects = objects;
        }

        /// <summary>
        /// conditions represent the latest available observations of a
        /// TemplateInstance's current state.
        /// </summary>
        [JsonProperty(PropertyName = "conditions")]
        public IList<Comgithubopenshiftoriginpkgtemplateapistemplatev1TemplateInstanceCondition> Conditions { get; set; }

        /// <summary>
        /// Objects references the objects created by the TemplateInstance.
        /// </summary>
        [JsonProperty(PropertyName = "objects")]
        public IList<Comgithubopenshiftoriginpkgtemplateapistemplatev1TemplateInstanceObject> Objects { get; set; }

    }
}
