// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace OpenShift.DotNet.Service.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// DockerStrategyOptions contains extra strategy options for Docker builds
    /// </summary>
    public partial class Comgithubopenshiftoriginpkgbuildapisbuildv1DockerStrategyOptions
    {
        /// <summary>
        /// Initializes a new instance of the
        /// Comgithubopenshiftoriginpkgbuildapisbuildv1DockerStrategyOptions
        /// class.
        /// </summary>
        public Comgithubopenshiftoriginpkgbuildapisbuildv1DockerStrategyOptions() { }

        /// <summary>
        /// Initializes a new instance of the
        /// Comgithubopenshiftoriginpkgbuildapisbuildv1DockerStrategyOptions
        /// class.
        /// </summary>
        public Comgithubopenshiftoriginpkgbuildapisbuildv1DockerStrategyOptions(IList<Iok8skubernetespkgapiv1EnvVar> buildArgs = default(IList<Iok8skubernetespkgapiv1EnvVar>), bool? noCache = default(bool?))
        {
            BuildArgs = buildArgs;
            NoCache = noCache;
        }

        /// <summary>
        /// Args contains any build arguments that are to be passed to Docker.
        /// See https://docs.docker.com/engine/reference/builder/#/arg for
        /// more details
        /// </summary>
        [JsonProperty(PropertyName = "buildArgs")]
        public IList<Iok8skubernetespkgapiv1EnvVar> BuildArgs { get; set; }

        /// <summary>
        /// noCache overrides the docker-strategy noCache option in the build
        /// config
        /// </summary>
        [JsonProperty(PropertyName = "noCache")]
        public bool? NoCache { get; set; }

    }
}
