// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace OpenShift.DotNet.Service.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// PersistentVolumeClaimSpec describes the common attributes of storage
    /// devices and allows a Source for provider-specific attributes
    /// </summary>
    public partial class Iok8skubernetespkgapiv1PersistentVolumeClaimSpec
    {
        /// <summary>
        /// Initializes a new instance of the
        /// Iok8skubernetespkgapiv1PersistentVolumeClaimSpec class.
        /// </summary>
        public Iok8skubernetespkgapiv1PersistentVolumeClaimSpec() { }

        /// <summary>
        /// Initializes a new instance of the
        /// Iok8skubernetespkgapiv1PersistentVolumeClaimSpec class.
        /// </summary>
        public Iok8skubernetespkgapiv1PersistentVolumeClaimSpec(IList<string> accessModes = default(IList<string>), Iok8skubernetespkgapiv1ResourceRequirements resources = default(Iok8skubernetespkgapiv1ResourceRequirements), Iok8sapimachinerypkgapismetav1LabelSelector selector = default(Iok8sapimachinerypkgapismetav1LabelSelector), string storageClassName = default(string), string volumeName = default(string))
        {
            AccessModes = accessModes;
            Resources = resources;
            Selector = selector;
            StorageClassName = storageClassName;
            VolumeName = volumeName;
        }

        /// <summary>
        /// AccessModes contains the desired access modes the volume should
        /// have. More info:
        /// https://kubernetes.io/docs/concepts/storage/persistent-volumes#access-modes-1
        /// </summary>
        [JsonProperty(PropertyName = "accessModes")]
        public IList<string> AccessModes { get; set; }

        /// <summary>
        /// Resources represents the minimum resources the volume should have.
        /// More info:
        /// https://kubernetes.io/docs/concepts/storage/persistent-volumes#resources
        /// </summary>
        [JsonProperty(PropertyName = "resources")]
        public Iok8skubernetespkgapiv1ResourceRequirements Resources { get; set; }

        /// <summary>
        /// A label query over volumes to consider for binding.
        /// </summary>
        [JsonProperty(PropertyName = "selector")]
        public Iok8sapimachinerypkgapismetav1LabelSelector Selector { get; set; }

        /// <summary>
        /// Name of the StorageClass required by the claim. More info:
        /// https://kubernetes.io/docs/concepts/storage/persistent-volumes#class-1
        /// </summary>
        [JsonProperty(PropertyName = "storageClassName")]
        public string StorageClassName { get; set; }

        /// <summary>
        /// VolumeName is the binding reference to the PersistentVolume
        /// backing this claim.
        /// </summary>
        [JsonProperty(PropertyName = "volumeName")]
        public string VolumeName { get; set; }

    }
}
