// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace OpenShift.DotNet.Service.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// A null or empty node selector term matches no objects.
    /// </summary>
    public partial class Iok8skubernetespkgapiv1NodeSelectorTerm
    {
        /// <summary>
        /// Initializes a new instance of the
        /// Iok8skubernetespkgapiv1NodeSelectorTerm class.
        /// </summary>
        public Iok8skubernetespkgapiv1NodeSelectorTerm() { }

        /// <summary>
        /// Initializes a new instance of the
        /// Iok8skubernetespkgapiv1NodeSelectorTerm class.
        /// </summary>
        public Iok8skubernetespkgapiv1NodeSelectorTerm(IList<Iok8skubernetespkgapiv1NodeSelectorRequirement> matchExpressions)
        {
            MatchExpressions = matchExpressions;
        }

        /// <summary>
        /// Required. A list of node selector requirements. The requirements
        /// are ANDed.
        /// </summary>
        [JsonProperty(PropertyName = "matchExpressions")]
        public IList<Iok8skubernetespkgapiv1NodeSelectorRequirement> MatchExpressions { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (MatchExpressions == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "MatchExpressions");
            }
            if (this.MatchExpressions != null)
            {
                foreach (var element in this.MatchExpressions)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
