// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace OpenShift.DotNet.Service.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Affinity is a group of affinity scheduling rules.
    /// </summary>
    public partial class Iok8skubernetespkgapiv1Affinity
    {
        /// <summary>
        /// Initializes a new instance of the Iok8skubernetespkgapiv1Affinity
        /// class.
        /// </summary>
        public Iok8skubernetespkgapiv1Affinity() { }

        /// <summary>
        /// Initializes a new instance of the Iok8skubernetespkgapiv1Affinity
        /// class.
        /// </summary>
        public Iok8skubernetespkgapiv1Affinity(Iok8skubernetespkgapiv1NodeAffinity nodeAffinity = default(Iok8skubernetespkgapiv1NodeAffinity), Iok8skubernetespkgapiv1PodAffinity podAffinity = default(Iok8skubernetespkgapiv1PodAffinity), Iok8skubernetespkgapiv1PodAntiAffinity podAntiAffinity = default(Iok8skubernetespkgapiv1PodAntiAffinity))
        {
            NodeAffinity = nodeAffinity;
            PodAffinity = podAffinity;
            PodAntiAffinity = podAntiAffinity;
        }

        /// <summary>
        /// Describes node affinity scheduling rules for the pod.
        /// </summary>
        [JsonProperty(PropertyName = "nodeAffinity")]
        public Iok8skubernetespkgapiv1NodeAffinity NodeAffinity { get; set; }

        /// <summary>
        /// Describes pod affinity scheduling rules (e.g. co-locate this pod
        /// in the same node, zone, etc. as some other pod(s)).
        /// </summary>
        [JsonProperty(PropertyName = "podAffinity")]
        public Iok8skubernetespkgapiv1PodAffinity PodAffinity { get; set; }

        /// <summary>
        /// Describes pod anti-affinity scheduling rules (e.g. avoid putting
        /// this pod in the same node, zone, etc. as some other pod(s)).
        /// </summary>
        [JsonProperty(PropertyName = "podAntiAffinity")]
        public Iok8skubernetespkgapiv1PodAntiAffinity PodAntiAffinity { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (this.NodeAffinity != null)
            {
                this.NodeAffinity.Validate();
            }
        }
    }
}
