// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace OpenShift.DotNet.Service.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Defines a set of pods (namely those matching the labelSelector
    /// relative to the given namespace(s)) that this pod should be
    /// co-located (affinity) or not co-located (anti-affinity) with, where
    /// co-located is defined as running on a node whose value of the label
    /// with key &lt;topologyKey&gt; tches that of any node on which a pod of
    /// the set of pods is running
    /// </summary>
    public partial class Iok8skubernetespkgapiv1PodAffinityTerm
    {
        /// <summary>
        /// Initializes a new instance of the
        /// Iok8skubernetespkgapiv1PodAffinityTerm class.
        /// </summary>
        public Iok8skubernetespkgapiv1PodAffinityTerm() { }

        /// <summary>
        /// Initializes a new instance of the
        /// Iok8skubernetespkgapiv1PodAffinityTerm class.
        /// </summary>
        public Iok8skubernetespkgapiv1PodAffinityTerm(Iok8sapimachinerypkgapismetav1LabelSelector labelSelector = default(Iok8sapimachinerypkgapismetav1LabelSelector), IList<string> namespaces = default(IList<string>), string topologyKey = default(string))
        {
            LabelSelector = labelSelector;
            Namespaces = namespaces;
            TopologyKey = topologyKey;
        }

        /// <summary>
        /// A label query over a set of resources, in this case pods.
        /// </summary>
        [JsonProperty(PropertyName = "labelSelector")]
        public Iok8sapimachinerypkgapismetav1LabelSelector LabelSelector { get; set; }

        /// <summary>
        /// namespaces specifies which namespaces the labelSelector applies to
        /// (matches against); null or empty list means "this pod's namespace"
        /// </summary>
        [JsonProperty(PropertyName = "namespaces")]
        public IList<string> Namespaces { get; set; }

        /// <summary>
        /// This pod should be co-located (affinity) or not co-located
        /// (anti-affinity) with the pods matching the labelSelector in the
        /// specified namespaces, where co-located is defined as running on a
        /// node whose value of the label with key topologyKey matches that
        /// of any node on which any of the selected pods is running. For
        /// PreferredDuringScheduling pod anti-affinity, empty topologyKey is
        /// interpreted as "all topologies" ("all topologies" here means all
        /// the topologyKeys indicated by scheduler command-line argument
        /// --failure-domains); for affinity and for RequiredDuringScheduling
        /// pod anti-affinity, empty topologyKey is not allowed.
        /// </summary>
        [JsonProperty(PropertyName = "topologyKey")]
        public string TopologyKey { get; set; }

    }
}
