// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace OpenShift.DotNet.Service.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Represents a Fibre Channel volume. Fibre Channel volumes can only be
    /// mounted as read/write once. Fibre Channel volumes support ownership
    /// management and SELinux relabeling.
    /// </summary>
    public partial class Iok8skubernetespkgapiv1FCVolumeSource
    {
        /// <summary>
        /// Initializes a new instance of the
        /// Iok8skubernetespkgapiv1FCVolumeSource class.
        /// </summary>
        public Iok8skubernetespkgapiv1FCVolumeSource() { }

        /// <summary>
        /// Initializes a new instance of the
        /// Iok8skubernetespkgapiv1FCVolumeSource class.
        /// </summary>
        public Iok8skubernetespkgapiv1FCVolumeSource(int lun, IList<string> targetWWNs, string fsType = default(string), bool? readOnlyProperty = default(bool?))
        {
            FsType = fsType;
            Lun = lun;
            ReadOnlyProperty = readOnlyProperty;
            TargetWWNs = targetWWNs;
        }

        /// <summary>
        /// Filesystem type to mount. Must be a filesystem type supported by
        /// the host operating system. Ex. "ext4", "xfs", "ntfs". Implicitly
        /// inferred to be "ext4" if unspecified.
        /// </summary>
        [JsonProperty(PropertyName = "fsType")]
        public string FsType { get; set; }

        /// <summary>
        /// Required: FC target lun number
        /// </summary>
        [JsonProperty(PropertyName = "lun")]
        public int Lun { get; set; }

        /// <summary>
        /// Optional: Defaults to false (read/write). ReadOnly here will force
        /// the ReadOnly setting in VolumeMounts.
        /// </summary>
        [JsonProperty(PropertyName = "readOnly")]
        public bool? ReadOnlyProperty { get; set; }

        /// <summary>
        /// Required: FC target worldwide names (WWNs)
        /// </summary>
        [JsonProperty(PropertyName = "targetWWNs")]
        public IList<string> TargetWWNs { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (TargetWWNs == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "TargetWWNs");
            }
        }
    }
}
