// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace OpenShift.DotNet.Service.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// VolumeMount describes a mounting of a Volume within a container.
    /// </summary>
    public partial class Iok8skubernetespkgapiv1VolumeMount
    {
        /// <summary>
        /// Initializes a new instance of the
        /// Iok8skubernetespkgapiv1VolumeMount class.
        /// </summary>
        public Iok8skubernetespkgapiv1VolumeMount() { }

        /// <summary>
        /// Initializes a new instance of the
        /// Iok8skubernetespkgapiv1VolumeMount class.
        /// </summary>
        public Iok8skubernetespkgapiv1VolumeMount(string mountPath, string name, bool? readOnlyProperty = default(bool?), string subPath = default(string))
        {
            MountPath = mountPath;
            Name = name;
            ReadOnlyProperty = readOnlyProperty;
            SubPath = subPath;
        }

        /// <summary>
        /// Path within the container at which the volume should be mounted.
        /// Must not contain ':'.
        /// </summary>
        [JsonProperty(PropertyName = "mountPath")]
        public string MountPath { get; set; }

        /// <summary>
        /// This must match the Name of a Volume.
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Mounted read-only if true, read-write otherwise (false or
        /// unspecified). Defaults to false.
        /// </summary>
        [JsonProperty(PropertyName = "readOnly")]
        public bool? ReadOnlyProperty { get; set; }

        /// <summary>
        /// Path within the volume from which the container's volume should be
        /// mounted. Defaults to "" (volume's root).
        /// </summary>
        [JsonProperty(PropertyName = "subPath")]
        public string SubPath { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (MountPath == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "MountPath");
            }
            if (Name == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Name");
            }
        }
    }
}
