// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace OpenShift.DotNet.Service.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// SelfSubjectAccessReviewSpec is a description of the access request.
    /// Exactly one of ResourceAuthorizationAttributes and
    /// NonResourceAuthorizationAttributes must be set
    /// </summary>
    public partial class Iok8skubernetespkgapisauthorizationv1SelfSubjectAccessReviewSpec
    {
        /// <summary>
        /// Initializes a new instance of the
        /// Iok8skubernetespkgapisauthorizationv1SelfSubjectAccessReviewSpec
        /// class.
        /// </summary>
        public Iok8skubernetespkgapisauthorizationv1SelfSubjectAccessReviewSpec() { }

        /// <summary>
        /// Initializes a new instance of the
        /// Iok8skubernetespkgapisauthorizationv1SelfSubjectAccessReviewSpec
        /// class.
        /// </summary>
        public Iok8skubernetespkgapisauthorizationv1SelfSubjectAccessReviewSpec(Iok8skubernetespkgapisauthorizationv1NonResourceAttributes nonResourceAttributes = default(Iok8skubernetespkgapisauthorizationv1NonResourceAttributes), Iok8skubernetespkgapisauthorizationv1ResourceAttributes resourceAttributes = default(Iok8skubernetespkgapisauthorizationv1ResourceAttributes))
        {
            NonResourceAttributes = nonResourceAttributes;
            ResourceAttributes = resourceAttributes;
        }

        /// <summary>
        /// NonResourceAttributes describes information for a non-resource
        /// access request
        /// </summary>
        [JsonProperty(PropertyName = "nonResourceAttributes")]
        public Iok8skubernetespkgapisauthorizationv1NonResourceAttributes NonResourceAttributes { get; set; }

        /// <summary>
        /// ResourceAuthorizationAttributes describes information for a
        /// resource access request
        /// </summary>
        [JsonProperty(PropertyName = "resourceAttributes")]
        public Iok8skubernetespkgapisauthorizationv1ResourceAttributes ResourceAttributes { get; set; }

    }
}
