// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace OpenShift.DotNet.Service.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// NodeDaemonEndpoints lists ports opened by daemons running on the Node.
    /// </summary>
    public partial class Iok8skubernetespkgapiv1NodeDaemonEndpoints
    {
        /// <summary>
        /// Initializes a new instance of the
        /// Iok8skubernetespkgapiv1NodeDaemonEndpoints class.
        /// </summary>
        public Iok8skubernetespkgapiv1NodeDaemonEndpoints() { }

        /// <summary>
        /// Initializes a new instance of the
        /// Iok8skubernetespkgapiv1NodeDaemonEndpoints class.
        /// </summary>
        public Iok8skubernetespkgapiv1NodeDaemonEndpoints(Iok8skubernetespkgapiv1DaemonEndpoint kubeletEndpoint = default(Iok8skubernetespkgapiv1DaemonEndpoint))
        {
            KubeletEndpoint = kubeletEndpoint;
        }

        /// <summary>
        /// Endpoint on which Kubelet is listening.
        /// </summary>
        [JsonProperty(PropertyName = "kubeletEndpoint")]
        public Iok8skubernetespkgapiv1DaemonEndpoint KubeletEndpoint { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (this.KubeletEndpoint != null)
            {
                this.KubeletEndpoint.Validate();
            }
        }
    }
}
