// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace OpenShift.DotNet.Service.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// ListMeta describes metadata that synthetic resources must have,
    /// including lists and various status objects. A resource may have only
    /// one of {ObjectMeta, ListMeta}.
    /// </summary>
    public partial class Iok8sapimachinerypkgapismetav1ListMeta
    {
        /// <summary>
        /// Initializes a new instance of the
        /// Iok8sapimachinerypkgapismetav1ListMeta class.
        /// </summary>
        public Iok8sapimachinerypkgapismetav1ListMeta() { }

        /// <summary>
        /// Initializes a new instance of the
        /// Iok8sapimachinerypkgapismetav1ListMeta class.
        /// </summary>
        public Iok8sapimachinerypkgapismetav1ListMeta(string resourceVersion = default(string), string selfLink = default(string))
        {
            ResourceVersion = resourceVersion;
            SelfLink = selfLink;
        }

        /// <summary>
        /// String that identifies the server's internal version of this
        /// object that can be used by clients to determine when objects have
        /// changed. Value must be treated as opaque by clients and passed
        /// unmodified back to the server. Populated by the system.
        /// Read-only. More info:
        /// https://git.k8s.io/community/contributors/devel/api-conventions.md#concurrency-control-and-consistency
        /// </summary>
        [JsonProperty(PropertyName = "resourceVersion")]
        public string ResourceVersion { get; set; }

        /// <summary>
        /// SelfLink is a URL representing this object. Populated by the
        /// system. Read-only.
        /// </summary>
        [JsonProperty(PropertyName = "selfLink")]
        public string SelfLink { get; set; }

    }
}
