// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace OpenShift.DotNet.Service.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// ServiceStatus represents the current status of a service.
    /// </summary>
    public partial class Iok8skubernetespkgapiv1ServiceStatus
    {
        /// <summary>
        /// Initializes a new instance of the
        /// Iok8skubernetespkgapiv1ServiceStatus class.
        /// </summary>
        public Iok8skubernetespkgapiv1ServiceStatus() { }

        /// <summary>
        /// Initializes a new instance of the
        /// Iok8skubernetespkgapiv1ServiceStatus class.
        /// </summary>
        public Iok8skubernetespkgapiv1ServiceStatus(Iok8skubernetespkgapiv1LoadBalancerStatus loadBalancer = default(Iok8skubernetespkgapiv1LoadBalancerStatus))
        {
            LoadBalancer = loadBalancer;
        }

        /// <summary>
        /// LoadBalancer contains the current status of the load-balancer, if
        /// one is present.
        /// </summary>
        [JsonProperty(PropertyName = "loadBalancer")]
        public Iok8skubernetespkgapiv1LoadBalancerStatus LoadBalancer { get; set; }

    }
}
