// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace OpenShift.DotNet.Service.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// An APIVersion represents a single concrete version of an object model.
    /// </summary>
    public partial class Iok8skubernetespkgapisextensionsv1beta1APIVersion
    {
        /// <summary>
        /// Initializes a new instance of the
        /// Iok8skubernetespkgapisextensionsv1beta1APIVersion class.
        /// </summary>
        public Iok8skubernetespkgapisextensionsv1beta1APIVersion() { }

        /// <summary>
        /// Initializes a new instance of the
        /// Iok8skubernetespkgapisextensionsv1beta1APIVersion class.
        /// </summary>
        public Iok8skubernetespkgapisextensionsv1beta1APIVersion(string name = default(string))
        {
            Name = name;
        }

        /// <summary>
        /// Name of this version (e.g. 'v1').
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

    }
}
