// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace OpenShift.DotNet.Service.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// NamespaceSpec describes the attributes on a Namespace.
    /// </summary>
    public partial class Iok8skubernetespkgapiv1NamespaceSpec
    {
        /// <summary>
        /// Initializes a new instance of the
        /// Iok8skubernetespkgapiv1NamespaceSpec class.
        /// </summary>
        public Iok8skubernetespkgapiv1NamespaceSpec() { }

        /// <summary>
        /// Initializes a new instance of the
        /// Iok8skubernetespkgapiv1NamespaceSpec class.
        /// </summary>
        public Iok8skubernetespkgapiv1NamespaceSpec(IList<string> finalizers = default(IList<string>))
        {
            Finalizers = finalizers;
        }

        /// <summary>
        /// Finalizers is an opaque list of values that must be empty to
        /// permanently remove object from storage. More info:
        /// https://git.k8s.io/community/contributors/design-proposals/namespaces.md#finalizers
        /// </summary>
        [JsonProperty(PropertyName = "finalizers")]
        public IList<string> Finalizers { get; set; }

    }
}
