// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace OpenShift.DotNet.Service.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// LimitRangeSpec defines a min/max usage limit for resources that match
    /// on kind.
    /// </summary>
    public partial class Iok8skubernetespkgapiv1LimitRangeSpec
    {
        /// <summary>
        /// Initializes a new instance of the
        /// Iok8skubernetespkgapiv1LimitRangeSpec class.
        /// </summary>
        public Iok8skubernetespkgapiv1LimitRangeSpec() { }

        /// <summary>
        /// Initializes a new instance of the
        /// Iok8skubernetespkgapiv1LimitRangeSpec class.
        /// </summary>
        public Iok8skubernetespkgapiv1LimitRangeSpec(IList<Iok8skubernetespkgapiv1LimitRangeItem> limits)
        {
            Limits = limits;
        }

        /// <summary>
        /// Limits is the list of LimitRangeItem objects that are enforced.
        /// </summary>
        [JsonProperty(PropertyName = "limits")]
        public IList<Iok8skubernetespkgapiv1LimitRangeItem> Limits { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (Limits == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Limits");
            }
        }
    }
}
