// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace OpenShift.DotNet.Service.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// A ThirdPartyResource is a generic representation of a resource, it is
    /// used by add-ons and plugins to add new resource types to the API.  It
    /// consists of one or more Versions of the api.
    /// </summary>
    public partial class Iok8skubernetespkgapisextensionsv1beta1ThirdPartyResource
    {
        /// <summary>
        /// Initializes a new instance of the
        /// Iok8skubernetespkgapisextensionsv1beta1ThirdPartyResource class.
        /// </summary>
        public Iok8skubernetespkgapisextensionsv1beta1ThirdPartyResource() { }

        /// <summary>
        /// Initializes a new instance of the
        /// Iok8skubernetespkgapisextensionsv1beta1ThirdPartyResource class.
        /// </summary>
        public Iok8skubernetespkgapisextensionsv1beta1ThirdPartyResource(string apiVersion = default(string), string description = default(string), string kind = default(string), Iok8sapimachinerypkgapismetav1ObjectMeta metadata = default(Iok8sapimachinerypkgapismetav1ObjectMeta), IList<Iok8skubernetespkgapisextensionsv1beta1APIVersion> versions = default(IList<Iok8skubernetespkgapisextensionsv1beta1APIVersion>))
        {
            ApiVersion = apiVersion;
            Description = description;
            Kind = kind;
            Metadata = metadata;
            Versions = versions;
        }

        /// <summary>
        /// APIVersion defines the versioned schema of this representation of
        /// an object. Servers should convert recognized schemas to the
        /// latest internal value, and may reject unrecognized values. More
        /// info:
        /// https://git.k8s.io/community/contributors/devel/api-conventions.md#resources
        /// </summary>
        [JsonProperty(PropertyName = "apiVersion")]
        public string ApiVersion { get; set; }

        /// <summary>
        /// Description is the description of this object.
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// Kind is a string value representing the REST resource this object
        /// represents. Servers may infer this from the endpoint the client
        /// submits requests to. Cannot be updated. In CamelCase. More info:
        /// https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds
        /// </summary>
        [JsonProperty(PropertyName = "kind")]
        public string Kind { get; set; }

        /// <summary>
        /// Standard object metadata
        /// </summary>
        [JsonProperty(PropertyName = "metadata")]
        public Iok8sapimachinerypkgapismetav1ObjectMeta Metadata { get; set; }

        /// <summary>
        /// Versions are versions for this third party object
        /// </summary>
        [JsonProperty(PropertyName = "versions")]
        public IList<Iok8skubernetespkgapisextensionsv1beta1APIVersion> Versions { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (this.Metadata != null)
            {
                this.Metadata.Validate();
            }
        }
    }
}
