// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace OpenShift.DotNet.Service.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// ContainerState holds a possible state of container. Only one of its
    /// members may be specified. If none of them is specified, the default
    /// one is ContainerStateWaiting.
    /// </summary>
    public partial class Iok8skubernetespkgapiv1ContainerState
    {
        /// <summary>
        /// Initializes a new instance of the
        /// Iok8skubernetespkgapiv1ContainerState class.
        /// </summary>
        public Iok8skubernetespkgapiv1ContainerState() { }

        /// <summary>
        /// Initializes a new instance of the
        /// Iok8skubernetespkgapiv1ContainerState class.
        /// </summary>
        public Iok8skubernetespkgapiv1ContainerState(Iok8skubernetespkgapiv1ContainerStateRunning running = default(Iok8skubernetespkgapiv1ContainerStateRunning), Iok8skubernetespkgapiv1ContainerStateTerminated terminated = default(Iok8skubernetespkgapiv1ContainerStateTerminated), Iok8skubernetespkgapiv1ContainerStateWaiting waiting = default(Iok8skubernetespkgapiv1ContainerStateWaiting))
        {
            Running = running;
            Terminated = terminated;
            Waiting = waiting;
        }

        /// <summary>
        /// Details about a running container
        /// </summary>
        [JsonProperty(PropertyName = "running")]
        public Iok8skubernetespkgapiv1ContainerStateRunning Running { get; set; }

        /// <summary>
        /// Details about a terminated container
        /// </summary>
        [JsonProperty(PropertyName = "terminated")]
        public Iok8skubernetespkgapiv1ContainerStateTerminated Terminated { get; set; }

        /// <summary>
        /// Details about a waiting container
        /// </summary>
        [JsonProperty(PropertyName = "waiting")]
        public Iok8skubernetespkgapiv1ContainerStateWaiting Waiting { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (this.Terminated != null)
            {
                this.Terminated.Validate();
            }
        }
    }
}
