// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace OpenShift.DotNet.Service.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// EnvVarSource represents a source for the value of an EnvVar.
    /// </summary>
    public partial class Iok8skubernetespkgapiv1EnvVarSource
    {
        /// <summary>
        /// Initializes a new instance of the
        /// Iok8skubernetespkgapiv1EnvVarSource class.
        /// </summary>
        public Iok8skubernetespkgapiv1EnvVarSource() { }

        /// <summary>
        /// Initializes a new instance of the
        /// Iok8skubernetespkgapiv1EnvVarSource class.
        /// </summary>
        public Iok8skubernetespkgapiv1EnvVarSource(Iok8skubernetespkgapiv1ConfigMapKeySelector configMapKeyRef = default(Iok8skubernetespkgapiv1ConfigMapKeySelector), Iok8skubernetespkgapiv1ObjectFieldSelector fieldRef = default(Iok8skubernetespkgapiv1ObjectFieldSelector), Iok8skubernetespkgapiv1ResourceFieldSelector resourceFieldRef = default(Iok8skubernetespkgapiv1ResourceFieldSelector), Iok8skubernetespkgapiv1SecretKeySelector secretKeyRef = default(Iok8skubernetespkgapiv1SecretKeySelector))
        {
            ConfigMapKeyRef = configMapKeyRef;
            FieldRef = fieldRef;
            ResourceFieldRef = resourceFieldRef;
            SecretKeyRef = secretKeyRef;
        }

        /// <summary>
        /// Selects a key of a ConfigMap.
        /// </summary>
        [JsonProperty(PropertyName = "configMapKeyRef")]
        public Iok8skubernetespkgapiv1ConfigMapKeySelector ConfigMapKeyRef { get; set; }

        /// <summary>
        /// Selects a field of the pod: supports metadata.name,
        /// metadata.namespace, metadata.labels, metadata.annotations,
        /// spec.nodeName, spec.serviceAccountName, status.hostIP,
        /// status.podIP.
        /// </summary>
        [JsonProperty(PropertyName = "fieldRef")]
        public Iok8skubernetespkgapiv1ObjectFieldSelector FieldRef { get; set; }

        /// <summary>
        /// Selects a resource of the container: only resources limits and
        /// requests (limits.cpu, limits.memory, requests.cpu and
        /// requests.memory) are currently supported.
        /// </summary>
        [JsonProperty(PropertyName = "resourceFieldRef")]
        public Iok8skubernetespkgapiv1ResourceFieldSelector ResourceFieldRef { get; set; }

        /// <summary>
        /// Selects a key of a secret in the pod's namespace
        /// </summary>
        [JsonProperty(PropertyName = "secretKeyRef")]
        public Iok8skubernetespkgapiv1SecretKeySelector SecretKeyRef { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (this.ConfigMapKeyRef != null)
            {
                this.ConfigMapKeyRef.Validate();
            }
            if (this.FieldRef != null)
            {
                this.FieldRef.Validate();
            }
            if (this.ResourceFieldRef != null)
            {
                this.ResourceFieldRef.Validate();
            }
            if (this.SecretKeyRef != null)
            {
                this.SecretKeyRef.Validate();
            }
        }
    }
}
